### ISSUE TITLE
Breaking Timere into Timere and Timedesc

### ISSUE THREAD

**Issue by darrenldl** [daypack-dev/timere#31]
@gasche: Just largely letting you know that after some discussion with @Drup, and the relevant issues, it seems overall nicer to keep timere to just "reasoning", and move the date time handling components into a new library, which we plan to name "Timedesc".

Right now I am gesturing between having
- layout of three separate types: `Timedesc.Date_time.t`, `Timedesc.Week_date_time.t` and `Timedesc.Ordinal_date_time.t`
- one unifying type `Timedesc.t` with "views" into different calendaring systems

intuition tells me latter is nicer. What you reckon?

**Comment by gasche** [comment]
To be honest, I don't know what `Week_date_time` and `Ordinal_date_time` are -- but I just looked into the documentation of `Timere.Week_date_time` to get an idea. `Date_time` and `Week_date_time` indeed look like isomorphic and rather-close representations of the same underlying thing, so I think that having a shared type with "views" in and out of the different representations may be sensible, but I don't have strong opinions, and also our though experiment with Span/Duration was not so convincing.

I'm afraid I'm indeed a borderline user of your library: I haven't used the pattern-matching stuff or reasoning" (not sure what reasoning we are talking about) that is your pride and I guess where the smarts are, I just use it to represent calendar datetimes at geographical timezones (which it does just fine after some doc clarification, and for which I don't know of another library in the OCaml ecosystem?). So please don't worry too much about me, do the breaking changes as you think is best, and I will adapt my code. (I moved from Timere 0.1.4 to Timere 0.3.1, everything changed yet it was easy to port my code.)

**Comment by darrenldl** [comment]
> To be honest, I don't know what Week_date_time and Ordinal_date_time are -- but I just looked into the documentation of Timere.Week_date_time to get an idea. Date_time and Week_date_time indeed look like isomorphic and rather-close representations of the same underlying thing, so I think that having a shared type with "views" in and out of the different representations may be sensible, but I don't have strong opinions, and also our thought experiment with Span/Duration was not so convincing.

Hm...I'll play around with the idea after the restructuring then.

> I'm afraid I'm indeed a borderline user of your library: I haven't used the pattern-matching stuff or reasoning" (not sure what reasoning we are talking about) that is your pride and I guess where the smarts are, I just use it to represent calendar datetimes at geographical timezones (which it does just fine after some doc clarification, and for which I don't know of another library in the OCaml ecosystem?). So please don't worry too much about me, do the breaking changes as you think is best, and I will adapt my code. (I moved from Timere 0.1.4 to Timere 0.3.1, everything changed yet it was easy to port my code.)

Honestly as the date time component grew, i have felt the itch to move it into a separate package, so this seems like a good point of finally committing to that idea.

Very initially scheduling was all we had in mind, but as things turned out, you can't do scheduling without a good calendar library. And as you said, unfortunately we didn't have one yet, so the calendar component grew much larger than we originally had in mind.

And I'll say that if I just want to get date time done, then I don't really want to care what other scheduling stuff the library offers, so I agree with your view (and likely most users' view as well I presume).

**Comment by darrenldl** [comment]
@gasche The separation is finally done (yay!). The new API doc if you happen to have the time to review: https://daypack-dev.github.io/timere/timedesc/Timedesc/index.html (you might need to clear cache/force refresh to load the newest version).

**Comment by gasche** [comment]
I had a look at the new documentation. Generally this is close to what we had before, and nice; the section on compatibility with `Ptime` will be useful, thanks!

One minor point: I find it very slightly confusing that the section [Date time](https://daypack-dev.github.io/timere/timedesc/Timedesc/index.html#date-time) starts with the `Time_zone` module followed by `type t`. By being visually close together it feels like `t` is directly related to timezones. I think the layout would be natural if the `Time_zone` module was included in the "Date time components" section above, so that `t` would be the first item of the "Date time" section, emphasizing its central importance.

(It could be nice also to have, for each "Date time components" module, a short sentence on the main documentation page describing what they represent. For `Date` and `Time_zone` is it rather clear, but personally I don´t find it obvious that `Time` represents points in time within a day, possibly because my native language (confusingly) uses "hour" to mean this: "what hour is it?".)

**Comment by darrenldl** [comment]
> One minor point: I find it very slightly confusing that the section Date time starts with the Time_zone module followed by type t. By being visually close together it feels like t is directly related to timezones. I think the layout would be natural if the Time_zone module was included in the "Date time components" section above, so that t would be the first item of the "Date time" section, emphasizing its central importance.

Done.

> (It could be nice also to have, for each "Date time components" module, a short sentence on the main documentation page describing what they represent. For Date and Time_zone is it rather clear, but personally I don´t find it obvious that Time represents points in time within a day, possibly because my native language (confusingly) uses "hour" to mean this: "what hour is it?".)

Good point - added some lines to make them clear. (I was tempted to name `Time` module to `Time_of_day`, but alas found it too cumbersome to use and couldn't think of a good short form.)
