### ISSUE TITLE
`timedesc` 0.7.0 not listed on OPAM repo

### ISSUE THREAD

**Issue by zbaylin** [daypack-dev/timere#59]
First, let me say thank you for such a well thought out library! I installed timere through OPAM which installed timere v0.7.0, but when I attempted to use the JS-based tzlocal provider, dune couldn't find it. After looking a bit more, I found that, while timedesc has a 0.7.0 release tag, the latest version on OPAM is 0.6.0. 

Is there a reason this version is not published? If it's considered incomplete I totally understand, but it would be helpful for me not to have to pin timedesc to a git tag if I don't have to.

Thanks!

**Comment by darrenldl** [comment]
Ah sorry - yeah it was in the process of being published but I was trying to figure out how to resolve some dependency issue and then got too busy.

https://github.com/ocaml/opam-repository/pull/20873

If it's the case that js_of_ocaml etc have been to be made mandatory, then I guess that'll have to do for 0.7.0 if that sounds reasonable to you.

There is ongoing work to slim down the set of dependencies, but I'm too busy to wrap that up right now.

**Comment by darrenldl** [comment]
@zbaylin Slowly wrapping up...will push to OPAM in next week hopefully - so many tiny breakages to fix after changing packaging structure.

**Comment by darrenldl** [comment]
Fully completed I believe, but still need to find time to set up fuzzing pipeline and run everything through it once before publishing.

**Comment by darrenldl** [comment]
Timedesc 0.8.0 PR has been submitted to opam repository, just waiting for it to be merged now.
