### ISSUE TITLE
`timere` 0.8.0 and up not available on opam

### ISSUE THREAD

**Issue by ElectreAAS** [daypack-dev/timere#69]
Similarly to #59, but this time for the `timere` and `timere-parse` packages, I wonder why the latest available version for both of these is `0.7.0` and not the latest on this repo. Specifically, on opam `timere` has an upper bound on `ocaml < 5.0`, which is not present on the latest.

Was there a specific reason for that upper bound that is not yet resolved?

Thank you!

**Comment by darrenldl** [comment]
For no release yet: there is a failure case detected by fuzzing for ISO week date time pattern matching, and I just haven't found time to investigate that properly.

For the upper bound: I don't recall actually - I think it might have been just adding that constraint to old packages probably by me (could also be by opam maintainer).

What is your use case? If it's (somewhat) urgent I can organise time this week to get it onto opam.

**Comment by ElectreAAS** [comment]
My use case is that I wanted to move a project which uses timere from ocaml 4.14 to 5.0.0

This isn't urgent in any way, so take all the time you need. For now I'm pinning timere on your repo and everything runs fine

**Comment by darrenldl** [comment]
I'm quite curious about what people use timere for - is the project public?

**Comment by ElectreAAS** [comment]
Yes the project is public, it's https://github.com/ocurrent/current-bench
I don't even really know what we use timere for to be honest

**Comment by ElectreAAS** [comment]
Any update on this?

**Comment by ElectreAAS** [comment]
No worries
Thanks for dropping by, and good luck with your PhD :)

**Comment by darrenldl** [comment]
Ah right ocurrent uses timere to drive scheduling. @art-w how extensive is timere used in ocurrent?

**Comment by darrenldl** [comment]
@ElectreAAS After some thinking, I think I'll pick the route to least resistance: I'll publish a version of Timere maybe next week and leave the bug fixing to future.

**Comment by darrenldl** [comment]
Pushed the experimental features to 0.9.0 release instead.

Submitted PR for 0.8.0 release: https://github.com/ocaml/opam-repository/pull/24858

**Comment by art-w** [comment]
Woh thanks a lot!

We use timere to benchmark the OCaml compiler on a weekly basis (for [`trunk`](https://bench.ci.dev/ocaml/ocaml/branch/trunk?worker=autumn&image=ocaml%2Fopam%3Adebian-11-ocaml-4.14), `5.0` and `5.1`, to check for regressions in the time it takes to compile large OCaml projects and the size of the binary artifacts that are produced by the compiler). Those benchmarks take a lot of time to complete, and so the weekly runs save on energy compared to the more aggressive "benchmark on every commit" that we normally do. I believe we have @punchagan to thanks for setting this up, if you have more questions!

Thanks again for your time(re :D), and good luck with your PhD!

**Comment by darrenldl** [comment]
Thanks! Fingers crossed haha.

Timere 0.8.0 PR at opam-repository has been accepted, closing this issue now.
