### ISSUE TITLE
Incorrect DST detection

### ISSUE THREAD

**Issue by copy** [daypack-dev/timere#74]
Converting the current time (in UTC) to Germany's local time yields 22:44:37.210709095+01:00, but I believe Germany is currently 2 hours ahead of UTC, and it's 23:44. The following reproduces the issue:

```ocaml
let () =
  let zone = Timedesc.Time_zone.make_exn "Europe/Berlin" in
  let t = Timedesc.of_iso8601_exn "2023-07-31T21:44:37.210709095Z" in
  let ts = Timedesc.to_timestamp_float_s_single t in
  let t = Timedesc.of_timestamp_float_s_exn ~tz_of_date_time:zone ts in
  Printf.printf "%s\n%!" (Timedesc.to_iso8601 t)
```

This is on timedesc-tzdb 1.2 (the latest version currently available on opam).

**Comment by darrenldl** [comment]
Thanks for reporting! Turns out there's a bug in parsing the compressed time zone database, leading to some bit flips.

I'll push a new version shortly.

**Comment by darrenldl** [comment]
Fixed by https://github.com/daypack-dev/timere/commit/287e21a23c5b40551bbc4e291b4425cddeada239

PR: https://github.com/ocaml/opam-repository/pull/24189
